# Generated by Django 2.2.12 on 2020-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=1000)),
                ('data_publi', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('foto', models.ImageField(null=True, upload_to='noticia/media')),
            ],
        ),
    ]
