# Generated by Django 2.2.12 on 2020-05-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionario', models.IntegerField()),
                ('questao', models.CharField(max_length=300)),
                ('isAlternativa', models.BooleanField()),
                ('isDissertativa', models.BooleanField()),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntaresposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.IntegerField(null=True)),
                ('resposta', models.TextField(null=True)),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('alternativa', models.CharField(max_length=300)),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.Pergunta')),
            ],
        ),
    ]
