# Generated by Django 2.2.12 on 2020-05-08 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('cod_municipio', models.CharField(max_length=50)),
                ('dependencia', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=150, null=True)),
                ('periodo', models.CharField(max_length=150, null=True)),
                ('curso', models.CharField(max_length=150, null=True)),
                ('isGraduacao', models.BooleanField()),
                ('isPosgraduacao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=None, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privateprofessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('ensinomedio', models.CharField(max_length=30, null=True)),
                ('inimagisterio', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('cod', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Professorescola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Privateprofessor')),
            ],
        ),
        migrations.AddField(
            model_name='privateprofessor',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Secretaria'),
        ),
        migrations.AddField(
            model_name='escola',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Secretaria'),
        ),
        migrations.AddField(
            model_name='escola',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil'),
        ),
    ]
