# Generated by Django 2.2.12 on 2020-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_formacao_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateprofessor',
            name='isAtivo',
            field=models.BooleanField(default=True),
        ),
    ]
