# Generated by Django 2.2.12 on 2020-05-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_privateprofessor_isativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorescola',
            old_name='ano',
            new_name='ano_inicio',
        ),
        migrations.AddField(
            model_name='professorescola',
            name='ano_fim',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='usuarios/media')),
                ('formacao', models.CharField(max_length=300)),
                ('leciona', models.CharField(max_length=300)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Escolaperfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAceito', models.BooleanField(default=False)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Professor')),
            ],
        ),
    ]
