# Generated by Django 2.2.12 on 2020-10-13 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200510_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateprofessor',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Escola'),
        ),
    ]
