# Generated by Django 2.2.12 on 2020-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_privateprofessor_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
